### ISSUE TITLE
App crashing on start up.

### ISSUE THREAD

**Issue by saivarshith2000** [rodriigovieira/rn-challenge-2#1]
Logcat output : 

`Process: com.rodrigo.vieira.expensestracker, PID: 1577
    java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:218)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:31)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:247)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1152)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:764)`

I seems like there is an issue in the build process.
These might be helpful :  [https://stackoverflow.com/a/42155931](url) 
[https://stackoverflow.com/a/45930469](url)

**Comment by rodriigovieira** [comment]
Thank you so much for pointing this out to me!

I just made a commit with an update that fixes this issue. Also, I already sent the new version in Google Play, I'm just waiting for their approval. The version code is 1.1.

Could you confirm to me that this issue has been fixed?

**Comment by saivarshith2000** [comment]
Sure, I'll try it out as soon as the new version is available on Playstore

**Comment by saivarshith2000** [comment]
Yep, it works fine now !!
